// Cuisine and location options for taste-select form

export const cuisineOptions = [
    // General Cuisines
    "Afghan",
    "African",
    "American",
    "Argentinian",
    "Asian Fusion",
    "Australian",
    "BBQ",
    "Brazilian",
    "Chinese",
    "French",
    "German",
    "Greek",
    "Halal",
    "Indian",
    "Indonesian",
    "Iranian",
    "Irish",
    "Israeli",
    "Italian",
    "Japanese",
    "Korean",
    "Lebanese",
    "Malaysian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Singaporean",
    "South African",
    "Spanish",
    "Swedish",
    "Swiss",
    "Taiwanese",
    "Thai",
    "Turkish",
    "Vietnamese",
  
    // Common Food Types
    "Bakery",
    "Burgers",
    "Cheesesteaks",
    "Chicken",
    "Comfort Food",
    "Curry",
    "Dim Sum",
    "Fish & Chips",
    "Fried Chicken",
    "Healthy",
    "Kebab",
    "Pizza",
    "Poke",
    "Ramen",
    "Salads",
    "Sandwiches",
    "Seafood",
    "Soul Food",
    "Steakhouse",
    "Street Food",
    "Sushi",
    "Tapas",
    "Tex-Mex",
    "Vegan",
    "Vegetarian",
    "Wings",
  
    // Specific Dishes & Styles
    "Bibimbap",
    "Banh Mi",
    "Pho",
    "Laksa",
    "Char Kway Teow",
    "Pad Thai",
    "Tom Yum",
    "Tacos",
    "Nachos",
    "Shawarma",
    "Gyoza",
    "Okonomiyaki",
    "Teriyaki",
    "Satay",
    "Donburi",
    "Yakitori",
    "Hotpot",
    "Korean Fried Chicken",
  
    // Meal Styles
    "Breakfast",
    "Brunch",
    "Dessert",
    "Snacks",
    "Drinks",
    "Pub Food",
  
    // Fast Food Chains
    "McDonald's",
    "KFC",
    "Hungry Jack's",
    "Oporto",
    "Domino's",
    "Pizza Hut",
    "Guzman y Gomez",
    "Subway",
    "Red Rooster",
    "Grill'd",
    "Nando's",
    "Sushi Hub",
    "Roll'd"
  ];
  

export const locationOptions = [
    "Alexandria",
    "Annandale",
    "Ashfield",
    "Auburn",
    "Balmain",
    "Bankstown",
    "Baulkham Hills",
    "Beacon Hill",
    "Beaconsfield",
    "Bellevue Hill",
    "Belmore",
    "Berala",
    "Berowra",
    "Bexley",
    "Blacktown",
    "Bondi",
    "Bondi Junction",
    "Bonnyrigg",
    "Botany",
    "Breakfast Point",
    "Brookvale",
    "Burwood",
    "Cammeray",
    "Campbelltown",
    "Camperdown",
    "Carlingford",
    "Carlton",
    "Castle Hill",
    "Chatswood",
    "Cheltenham",
    "Cherrybrook",
    "Chippendale",
    "Clovelly",
    "Concord",
    "Concord West",
    "Coogee",
    "Cremorne",
    "Cronulla",
    "Crows Nest",
    "Darling Harbour",
    "Darling Point",
    "Darlinghurst",
    "Dee Why",
    "Denistone",
    "Dulwich Hill",
    "Eastgardens",
    "Eastlakes",
    "Eastwood",
    "Epping",
    "Erskineville",
    "Five Dock",
    "Forest Lodge",
    "Gladesville",
    "Glebe",
    "Granville",
    "Greenacre",
    "Greenwich",
    "Guildford",
    "Haberfield",
    "Harris Park",
    "Haymarket",
    "Homebush",
    "Homebush West",
    "Hornsby",
    "Hurstville",
    "Kensington",
    "Kings Cross",
    "Kingsford",
    "Kingsgrove",
    "Kogarah",
    "Lane Cove",
    "Leichhardt",
    "Lidcombe",
    "Lilyfield",
    "Liverpool",
    "Macquarie Park",
    "Manly",
    "Maroubra",
    "Mascot",
    "Marrickville",
    "Marsfield",
    "Milsons Point",
    "Moore Park",
    "Mortdale",
    "Mosman",
    "Mount Druitt",
    "Neutral Bay",
    "Newtown",
    "North Parramatta",
    "North Ryde",
    "North Sydney",
    "Northbridge",
    "Oatley",
    "Paddington",
    "Parramatta",
    "Pennant Hills",
    "Petersham",
    "Potts Point",
    "Pymble",
    "Pyrmont",
    "Redfern",
    "Rhodes",
    "Rockdale",
    "Rose Bay",
    "Rosebery",
    "Rozelle",
    "Rydalmere",
    "Ryde",
    "Seaforth",
    "St Leonards",
    "St Peters",
    "Stanmore",
    "Strathfield",
    "Summer Hill",
    "Surry Hills",
    "Sydney CBD",
    "Tempe",
    "Turramurra",
    "Ultimo",
    "Vaucluse",
    "Wahroonga",
    "Waterloo",
    "Watsons Bay",
    "Waverton",
    "Wentworth Point",
    "West Ryde",
    "Wetherill Park",
    "Willoughby",
    "Wolli Creek",
    "Woollahra",
    "Woolloomooloo",
    "Zetland"
  ];
  